name: Build ZAIInnov APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Install Android SDK
        run: |
          mkdir -p $GITHUB_WORKSPACE/android-sdk/cmdline-tools
          cd $GITHUB_WORKSPACE/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
          unzip tools.zip
          rm tools.zip
          mv cmdline-tools latest

          # Accepter les licences et installer les outils nécessaires
          yes | $GITHUB_WORKSPACE/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$GITHUB_WORKSPACE/android-sdk --licenses
          $GITHUB_WORKSPACE/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$GITHUB_WORKSPACE/android-sdk "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Create symlinks for Buildozer compatibility
        run: |
          mkdir -p /home/runner/.buildozer/android/platform/android-sdk/tools/bin
          ln -s $GITHUB_WORKSPACE/android-sdk/cmdline-tools/latest/bin/sdkmanager /home/runner/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager
          ln -s $GITHUB_WORKSPACE/android-sdk/build-tools /home/runner/.buildozer/android/platform/android-sdk/build-tools
          ln -s $GITHUB_WORKSPACE/android-sdk/platforms /home/runner/.buildozer/android/platform/android-sdk/platforms
          ln -s $GITHUB_WORKSPACE/android-sdk/platform-tools /home/runner/.buildozer/android/platform/android-sdk/platform-tools

      - name: Set PATH
        run: |
          echo "$GITHUB_WORKSPACE/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/android-sdk/platform-tools" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/android-sdk/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Build APK with Buildozer
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ZAIInnov-APK
          path: bin/*.apk
