name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Ensure Android Build Tools Installed
        run: |
          yes | sdkmanager "build-tools;34.0.0"
          yes | sdkmanager "platforms;android-34"

      - name: Set environment variables
        run: |
          echo "ANDROIDSDK=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "PATH=$PATH:$ANDROID_SDK_ROOT/build-tools/34.0.0" >> $GITHUB_ENV

      - name: Build APK with Buildozer
        run: |
          buildozer android debug
